#!/bin/bash

# Build the client
stack build --stack-yaml=frontend/stack.yaml

# Copy over the javascript
# rm -f server/static/all.js
# cp $(stack path --stack-yaml=client/stack.yaml --local-install-root)/bin/client.jsexe/all.js server/static/all.js

# Build the server
# stack build --stack-yaml=server/stack.yaml
