#!/bin/bash

# Build clientside frontend Miso app
stack build --fast --stack-yaml stack-ghcjs.yaml

# Build serverside backend Miso/Servant
stack build --fast --stack-yaml stack.yaml

# Copy over the javascript
rm backend/static/all.js
cp $(stack path --stack-yaml stack-ghcjs.yaml --local-install-root)/bin/frontend.jsexe/all.js backend/static/all.js

